### ISSUE TITLE
Please update this

### ISSUE THREAD

**Issue by EpicPinkCreeper** [Falkirks/iControlU#2]
This was such a great plugin but it hasn't been updated for a while

**Comment by falkirks** [comment]
Is it missing anything?

**Comment by EpicPinkCreeper** [comment]
I meant for the newest version of pocketmine.

**Comment by EpicPinkCreeper** [comment]
[12:56:25] [Server thread/ERROR]: Could not load plugin 'iControlU': Incompatible API version (plugin requires one of: 1.6.0)

**Comment by brexmania123** [comment]
look at the dates they are different

**Comment by falkirks** [comment]
@brexmania123 You aren't making sense. #6 was closed because it was an update request. I will only leave one update request open per repo.

**Comment by brexmania123** [comment]
well it still needs to be updated to be compatible with 3.0.0-ALPHA11. At this time we cant use it even if we changed the api ourselves. you really need to update this to use this version. i cant troll people without it

**Comment by brexmania123** [comment]
but still you havent updated it since 3 years ago. it only works with 1.6.0 not 3.0.0-ALPHA11, so hurry up and update this plugin

**Comment by falkirks** [comment]
@brexmania123 As I have said in several other places, I am not the only one who can update this plugin. You could get numerous other people to do it, or do it yourself. And furthermore, I don't have an obligation to provide you an updated version. Nevertheless, this plugin is on the top of my list to receive updates, so it should happen soon. Just do try to keep in mind that I am providing all of this code for free and I do have other things to do in my life.

And the reason it hasn't been updated in 3 years is because the code isn't written in an ideal way, so any substantial update would potentially require rewriting the whole plugin.

**Comment by t0mtee** [comment]
@Falkirks Ok cool.
